name: N2N_freebsd

on:
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: freebsd-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install build dependencies
        run: |
          sudo pkg install -y gcc     # 安装编译工具链
          sudo pkg install -y make    # 安装make工具
          sudo pkg install -y cmake   # 安装cmake（如果需要）

      - name: Download source code
        run: |
          git clone --recursive https://github.com/xf110/n2n-2.8.x 
          cd n2n-2.8.x
          # 自定义编译选项，根据需要调整
          sed -i 's/USE AES" ON/USE AES" OFF/g' ./CMakeLists.txt

      - name: Build n2n
        run: |
          cd n2n-2.8.x
          mkdir build && cd build
          cmake -DCMAKE_EXE_LINKER_FLAGS=-static ..  # 静态编译，根据需要调整
          make

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        if: always()  # 无论之前步骤是否失败都上传artifact
        with:
          name: n2n-2.8.x-freebsd
          path: n2n-2.8.x/build/edge  # 这里需要根据实际情况调整路径
