name: Build and Test n2n on FreeBSD amd64

on:
  push:
    branches:
      - main  # 当 main 分支有推送时触发
  workflow_dispatch:  # 允许手动触发工作流程

env:
  TZ: Asia/Shanghai  # 设置时区

jobs:
  build:
    runs-on: freebsd-latest  # 在最新的 FreeBSD runner 上运行作业

    steps:
      - name: Check out repository  # 检出代码库
        uses: actions/checkout@v2

      - name: Install build dependencies  # 安装编译依赖
        run: |
          sudo pkg install -y gcc     # 安装编译工具链
          sudo pkg install -y make    # 安装make工具
          sudo pkg install -y cmake   # 安装cmake（如果需要）

      - name: Download n2n source code  # 下载 n2n 源码
        run: |
          git clone --recursive https://github.com/ntop/n2n.git
          cd n2n

      - name: Configure and Build n2n  # 配置并构建 n2n
        run: |
          mkdir build && cd build
          cmake ..
          make

      - name: Run Tests  # 运行测试（如果有的话）
        run: |
          ctest  # 使用 ctest 命令运行测试

      - name: Package and Upload Artifact  # 打包并上传构建产物
        uses: actions/upload-artifact@v2
        with:
          name: n2n-binary-freebsd-amd64  # 指定 artifact 的名称
          path: path/to/your/n2n/executable  # 替换为实际的二进制文件路径
