name: N2N多线程版
on:
  workflow_dispatch:
env:
  TZ: Asia/Shanghai
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: arm64
            tool: aarch64-linux-musl
          - name: mipsel
            tool: mipsel-linux-musl
          - name: amd64
            tool: x86_64-linux-musl
    steps:
      -
        name: 检查代码仓库
        uses: actions/checkout@main
      - 
        name: 下载源码并编译${{ matrix.name }}
        run: |
          ##########建立编译链目录，下载交叉编译链并解压##########
          sudo mkdir -p /opt/x-tools
          wget -q https://musl.cc/${{ matrix.tool }}-cross.tgz
          sudo tar xvf ${{ matrix.tool }}-cross.tgz -C /opt/x-tools
          #给upx3.95赋予执行权限
          sudo chmod +x upx3.95
          ##########下载源码##########
          #克隆源码
          git clone --recursive https://github.com/xf110/n2n-2.8.x 
          #进入编译目录
          cd n2n-2.8.x
          #--------自定义编译选项，要阅读CMakeLists.txt调整参数---------------------------
          #关闭加密
          sed -i 's/USE AES" ON/USE AES" OFF/g' ./CMakeLists.txt
          #----------------------------------------------------------------------------
          #定义编译器位置
          export CC=/opt/x-tools/${{ matrix.tool }}-cross/bin/${{ matrix.tool }}-gcc
          #二进制文件存放目录
          mkdir build && cd build
          #静态编译配置
          cmake -DCMAKE_EXE_LINKER_FLAGS=-static ..  #静态编译 去掉-DCMAKE_EXE_LINKER_FLAGS=-static为动态编译
          #开始编译
          make 
          #剥离无用代码
          /opt/x-tools/${{ matrix.tool }}-cross/bin/${{ matrix.tool }}-strip edge
          #压缩###尽量不要压缩
          ../../upx3.95 --best --ultra-brute edge
          #改名
          mv edge edge_${{ matrix.name }}
      - 
        name: 上传
        uses: actions/upload-artifact@master
        if: always()
        with:
         name: n2n-2.8.x-${{ matrix.name }}
         path: n2n-2.8.x/build/edge_${{ matrix.name }}
      
      - name: 发布
        uses: ncipollo/release-action@main
        with:
          tag: wg-tool
          artifacts: n2n-2.8.x/build/edge_${{ matrix.name }}
          token: ${{ secrets.test }}
          allowUpdates: true
          omitBodyDuringUpdate: true
     
      
