
name: 编译工具

on:
  workflow_dispatch
env:
  TZ: Asia/Shanghai
  fw: padavan
jobs:
  
   build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
           
      - 
        name: 编译链下载
       
      
           
           
        run: |
          git clone --recursive https://github.com/heiher/natmap /opt/natmap
          rm -rf /opt/natmap/hev-task-system
          git clone https://github.com/heiher/hev-task-system /opt/natmap/hev-task-system
      
          
          padavan(){
          wget -c https://github.com/lmq8267/n2n-2.8.x/releases/download/toolchain/host.zip -P /opt/gcc/ 
          unzip /opt/gcc/host.zip -d /opt/gcc/ 
          sudo chmod 777 -R /opt/gcc
          dir=/opt/gcc/host/bin/mipsel-linux
          }
          
          openwrt(){
          wget -c https://github.com/xf110/tool/releases/download/1.0.0/openwrt-toolchain-23.05.0-rc3-ramips-mt7621_gcc-12.3.0_musl.Linux-x86_64.tar.xz -P /opt/openwrt/gcc/
          tar xf /opt/openwrt/gcc/mipsel-linux-uclibc-by-hanwckf.tar.gz -C /opt/openwrt/gcc/
          dir=/opt/openwrt/gcc/openwrt-toolchain-23.05.0-rc3-ramips-mt7621_gcc-12.3.0_musl.Linux-x86_64/toolchain-mipsel_24kc_gcc-12.3.0_musl/bin/mipsel-openwrt-linux-musl
          }
          
          if [ "$fw" = "padavan" ] ; then
          padavan
          fi
          if [ "$fw" = "openwrt" ] ; then
          openwrt
          fi
      - 
        name: 编译
       
      
           
           
        run: |
         
          #sudo chmod 777 -R /opt/$fw/gcc
          export STAGING_DIR=/opt/padavan/gcc/host
          export PATH=$PATH:/opt/padavan/gcc/host/bin
          export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/padavan/gcc/host/lib
          cd /opt/natmap/
          #make ENABLE_STATIC=1 CROSS_PREFIX=/opt/gcc/openwrt-toolchain-23.05.0-rc3-ramips-mt7621_gcc-12.3.0_musl.Linux-x86_64/toolchain-mipsel_24kc_gcc-12.3.0_musl/bin/mipsel-openwrt-linux-musl-
          make CROSS_PREFIX=${dir}-

         
      
      
          wget -c https://github.com/xf110/tool/releases/download/1.0.0/upx-3.95-amd64_linux.tar.xz -P /opt
          tar -xvf /opt/upx-3.95-amd64_linux.tar.xz -C /opt
          chmod 777 /opt/upx-3.95-amd64_linux/upx
          cd /opt/natmap/bin
          ${dir}-strip natmap     
          /opt/upx-3.95-amd64_linux/upx --lzma --best natmap
               
      - 
        name: 发布
        uses: actions/upload-artifact@master
        if: always()
        with:
         name: natmap-${fw}
         path: /opt/natmap/bin/natmap
