
name: 编译工具

on:
  workflow_dispatch
env:
  TZ: Asia/Shanghai

jobs:
  
   build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - 
        name: 下载
        run: |
          padavan(){
        
          wget -c https://github.com/xf110/tool/releases/download/1.0.0/host.zip -P /opt/padavan/gcc/
          unzip /opt/padavan/gcc/host.zip -d /opt/padavan/gcc/
          ls /opt/padavan/gcc
          }
          https://github.com/xf110/tool/releases/download/1.0.0/host.zip(){
          wget -c https://github.com/xf110/tool/releases/download/1.0.0/mipsel-linux-uclibc-by-hanwckf.tar.gz -P /opt/openwrt/gcc/
          tar xf /opt/openwrt/gcc/mipsel-linux-uclibc-by-hanwckf.tar.gz -C /opt/openwrt/gcc/
          
          cd /opt/openwrt/gcc
          ls 
          }
          fw=pa
          if [ $fw="pa" ] ; then
          padavan
          fi
          if [ $fw="op" ] ; then
          openwrt
          fi
