name: vnt
on:
  workflow_dispatch:
env:
  TZ: Asia/Shanghai
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: aarch64-unknown-linux-musl
            tool: aarch64-linux-musl
            rv: 1.81
          - name: mipsel-unknown-linux-musl
            tool: mipsel-linux-musl
            rv: 1.81
          - name: x86_64-unknown-linux-musl
            tool: x86_64-linux-musl
            rv: 1.81
    steps:
      -
        name: 检查代码仓库
        uses: actions/checkout@v3      
      - 
        name: 下载编译器和源码并编译
        run: |
          chmod +x upx3.95
          sudo mkdir -p /opt/x-tools
          wget -q https://github.com/xf110/build-test/releases/download/n2n2/${{ matrix.tool }}-cross.tgz
          tar -xf ${{ matrix.tool }}-cross.tgz -C /opt/x-tools
          #####安装rustup#######
          rustup install ${{ matrix.rv }}
          rustup default ${{ matrix.rv }}
          #####此版本rustup支持的架构列表#####
          rustup target list
          #####添加架构#####
          rustup target add ${{ matrix.name }}
          cat >>~/.cargo/config <<EOF
          [target.${{ matrix.name }}]
          linker = "/opt/x-tools/${{ matrix.tool }}-cross/bin/${{ matrix.tool }}-gcc"
          rustflags = ["-C", "target-feature=+crt-static","-C", "strip=symbols"]
          EOF
          git clone --recursive -b 1.2.x https://github.com/lbl8603/vnt 
          cd vnt
          rm -f Cargo.lock
          cargo generate-lockfile
          cargo build --package vnt-cli --target=${{ matrix.name }} --release --no-default-features
          ../upx3.95 --lzma --best target/${{ matrix.name }}/release/vnt-cli     
      - 
        name: 上传
        uses: actions/upload-artifact@master
        if: always()
        with:
         name: vnt_1.2.9_${{ matrix.name }}
         path: vnt/target/${{ matrix.name }}/release/vnt-cli
